apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: circleci-release-agent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: https://circleci-public.github.io/cci-k8s-release-agent
    chart: circleci-release-agent
    targetRevision: "*"
    helm:
      values: |
        tokenSecret:
          create: false
          name: circleci-release-agent-token
        managedNamespaces:
          - release-test
        podAnnotations:
          ad.datadoghq.com/manager.checks: |
            {
              "openmetrics": {
                "instances": [
                  {
                    "openmetrics_endpoint": "http://%%host%%:8080/metrics",
                    "namespace": "circleci_release_agent",
                    "metrics": [".*"]
                  }
                ]
              }
            }
          ad.datadoghq.com/manager.logs: '[{"source":"circleci-release-agent","service":"circleci-release-agent"}]'
  destination:
    server: https://kubernetes.default.svc
    namespace: circleci-release-agent-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
